apiVersion: v1
kind: Service
metadata:
  name: auth0-manager-service
spec:
  type: LoadBalancer  # For external access, use NodePort for internal or development testing
  ports:
    - port: 80
      targetPort: 5001
  selector:
    app: auth0-manager
